### ISSUE TITLE
130x65 bitmap logos

### ISSUE THREAD

**Issue by yellow-panther** [rchastain/luciole#2]
Bonjour Roland,
cf. 
[Alouette + Luciole logos.zip](https://github.com/rchastain/luciole/files/3243895/Alouette.%2B.Luciole.logos.zip)

Smirf comme un logiciel à source ouverte n´existe (plus) cf. http://www.open-aurec.com/wbforum/viewtopic.php?f=4&t=194

Salutations,

**Comment by rchastain** [comment]
Bonjour Norbert !
Merci pour les belles images, et pour l'information concernant _Smirf_.
Amicalement.
Roland

**Comment by rchastain** [comment]
Bonjour Norbert !
Voici ce que j'ai fait à partir de tes images, au cas où cela t'intéresse.
Amicalement.
Roland
[logos-alouette.zip](https://github.com/rchastain/luciole/files/3268979/logos-alouette.zip)
