### ISSUE TITLE
Alouette (hélicoptère) et Luciole (avion)

### ISSUE THREAD

**Issue by yellow-panther** [rchastain/luciole#3]
Salut Roland,
j´ai trouvé quelques photos sur ce sujet ici:

https://fr.wikipedia.org/wiki/SNCASE_SE.3130_Alouette_II
https://fr.wikipedia.org/wiki/Sud-Aviation_SA316_Alouette_III
https://fr.wikipedia.org/wiki/Caudron_C.270
https://fr.wikipedia.org/wiki/Colomban_MC-30 

Merci beaucoup pour le compilé du programme des échecs Sapeli (=sabre) win 1.34 et 1.35
Salutations,

**Comment by rchastain** [comment]
Très belles photos. Merci !

**Comment by rchastain** [comment]
Je ne savais pas qu'il y avait un avion appelé _Luciole_. Merci beaucoup !
